/*
 * Semux API
 * Semux is an experimental high-performance blockchain platform that powers decentralized application.
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.semux.sdk.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.semux.sdk.client.model.DelegateType;

/**
 * AccountVoteType
 */

public class AccountVoteType {
  @JsonProperty("delegate")
  private DelegateType delegate = null;

  @JsonProperty("votes")
  private String votes = null;

  public AccountVoteType delegate(DelegateType delegate) {
    this.delegate = delegate;
    return this;
  }

   /**
   * Get delegate
   * @return delegate
  **/
  @ApiModelProperty(value = "")
  public DelegateType getDelegate() {
    return delegate;
  }

  public void setDelegate(DelegateType delegate) {
    this.delegate = delegate;
  }

  public AccountVoteType votes(String votes) {
    this.votes = votes;
    return this;
  }

   /**
   * Total votes from this account to the delegate
   * @return votes
  **/
  @ApiModelProperty(value = "Total votes from this account to the delegate")
  public String getVotes() {
    return votes;
  }

  public void setVotes(String votes) {
    this.votes = votes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountVoteType accountVoteType = (AccountVoteType) o;
    return Objects.equals(this.delegate, accountVoteType.delegate) &&
        Objects.equals(this.votes, accountVoteType.votes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delegate, votes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountVoteType {\n");
    
    sb.append("    delegate: ").append(toIndentedString(delegate)).append("\n");
    sb.append("    votes: ").append(toIndentedString(votes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

