/*
 * Semux API
 * Semux is an experimental high-performance blockchain platform that powers decentralized application.
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.semux.sdk.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.semux.sdk.client.model.ApiHandlerResponse;

/**
 * GetVotesResponse
 */

public class GetVotesResponse extends ApiHandlerResponse {
  @JsonProperty("result")
  private Map<String, String> result = null;

  public GetVotesResponse result(Map<String, String> result) {
    this.result = result;
    return this;
  }

  public GetVotesResponse putResultItem(String key, String resultItem) {
    if (this.result == null) {
      this.result = new HashMap<String, String>();
    }
    this.result.put(key, resultItem);
    return this;
  }

   /**
   * A map of [voter address] &#x3D;&gt; [votes]
   * @return result
  **/
  @ApiModelProperty(value = "A map of [voter address] => [votes]")
  public Map<String, String> getResult() {
    return result;
  }

  public void setResult(Map<String, String> result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetVotesResponse getVotesResponse = (GetVotesResponse) o;
    return Objects.equals(this.result, getVotesResponse.result) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetVotesResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

