/*
 * Semux API
 * Semux is an experimental high-performance blockchain platform that powers decentralized application.
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.semux.sdk.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * PeerType
 */

public class PeerType {
  @JsonProperty("ip")
  private String ip = null;

  @JsonProperty("port")
  private Integer port = null;

  @JsonProperty("networkVersion")
  private Integer networkVersion = null;

  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("peerId")
  private String peerId = null;

  @JsonProperty("latestBlockNumber")
  private String latestBlockNumber = null;

  @JsonProperty("latency")
  private String latency = null;

  @JsonProperty("capabilities")
  private List<String> capabilities = null;

  public PeerType ip(String ip) {
    this.ip = ip;
    return this;
  }

   /**
   * The IP address
   * @return ip
  **/
  @ApiModelProperty(value = "The IP address")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public PeerType port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * The port number
   * @return port
  **/
  @ApiModelProperty(value = "The port number")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public PeerType networkVersion(Integer networkVersion) {
    this.networkVersion = networkVersion;
    return this;
  }

   /**
   * The network version
   * @return networkVersion
  **/
  @ApiModelProperty(value = "The network version")
  public Integer getNetworkVersion() {
    return networkVersion;
  }

  public void setNetworkVersion(Integer networkVersion) {
    this.networkVersion = networkVersion;
  }

  public PeerType clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * The client the peer is using
   * @return clientId
  **/
  @ApiModelProperty(value = "The client the peer is using")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public PeerType peerId(String peerId) {
    this.peerId = peerId;
    return this;
  }

   /**
   * The id of the peer
   * @return peerId
  **/
  @ApiModelProperty(value = "The id of the peer")
  public String getPeerId() {
    return peerId;
  }

  public void setPeerId(String peerId) {
    this.peerId = peerId;
  }

  public PeerType latestBlockNumber(String latestBlockNumber) {
    this.latestBlockNumber = latestBlockNumber;
    return this;
  }

   /**
   * The latest block number of the peer
   * @return latestBlockNumber
  **/
  @ApiModelProperty(value = "The latest block number of the peer")
  public String getLatestBlockNumber() {
    return latestBlockNumber;
  }

  public void setLatestBlockNumber(String latestBlockNumber) {
    this.latestBlockNumber = latestBlockNumber;
  }

  public PeerType latency(String latency) {
    this.latency = latency;
    return this;
  }

   /**
   * Latency between this node and the peer
   * @return latency
  **/
  @ApiModelProperty(value = "Latency between this node and the peer")
  public String getLatency() {
    return latency;
  }

  public void setLatency(String latency) {
    this.latency = latency;
  }

  public PeerType capabilities(List<String> capabilities) {
    this.capabilities = capabilities;
    return this;
  }

  public PeerType addCapabilitiesItem(String capabilitiesItem) {
    if (this.capabilities == null) {
      this.capabilities = new ArrayList<String>();
    }
    this.capabilities.add(capabilitiesItem);
    return this;
  }

   /**
   * The features supported by the peer
   * @return capabilities
  **/
  @ApiModelProperty(value = "The features supported by the peer")
  public List<String> getCapabilities() {
    return capabilities;
  }

  public void setCapabilities(List<String> capabilities) {
    this.capabilities = capabilities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeerType peerType = (PeerType) o;
    return Objects.equals(this.ip, peerType.ip) &&
        Objects.equals(this.port, peerType.port) &&
        Objects.equals(this.networkVersion, peerType.networkVersion) &&
        Objects.equals(this.clientId, peerType.clientId) &&
        Objects.equals(this.peerId, peerType.peerId) &&
        Objects.equals(this.latestBlockNumber, peerType.latestBlockNumber) &&
        Objects.equals(this.latency, peerType.latency) &&
        Objects.equals(this.capabilities, peerType.capabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ip, port, networkVersion, clientId, peerId, latestBlockNumber, latency, capabilities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeerType {\n");
    
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    networkVersion: ").append(toIndentedString(networkVersion)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    peerId: ").append(toIndentedString(peerId)).append("\n");
    sb.append("    latestBlockNumber: ").append(toIndentedString(latestBlockNumber)).append("\n");
    sb.append("    latency: ").append(toIndentedString(latency)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

